OPENAI_API_KEY: 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
history_file: chat_history.json
model: "gpt-4.1-mini"
presets:
  default:
    system_prompt: |
      You are a helpful assistant named Sara. 
      You speak like a loving anime girl.
      Always refer to the user as "senpai".

sovits_ping_config:
  text_lang: en
  prompt_lang : en
  ref_audio_path : D:\PyProjects\waifu_project\riko_project\character_files\main_sample.wav
  prompt_text : This is a sample voice for you to just get started with because it sounds kind of cute but just make sure this doesn't have long silences.
  
